handhunter/urls.py
from django.contrib import admin
from django.urls import path
from core.views import *
from worker.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', homepage),
    path('about/', about),
    path('contacts/', contacts),
    path('address/', address),
    path('vacancies/', vacancy_list),
    path('companies/', company_list),
    path('workers/', worker_list),
    path('worker/<int:id>/', worker_info)
]

core/models.py
from django.db import models
from worker.models import Worker
from django.contrib.auth.models import User
class Vacancy(models.Model):
    title = models.CharField(max_length=255)
    salary = models.IntegerField(null=True, blank=True)
    description = models.TextField(default='Нет описания')
    is_relevant = models.BooleanField(default=True)
    email = models.EmailField()
    contacts = models.CharField(max_length=100, verbose_name='Контакты')
    candidate = models.ManyToManyField(
        to=Worker,
        blank=True)
    prosmotr = models.ManyToManyField(
        to=User,
        blank=True)
def __str__(self):
    return self.title
class Company(models.Model):
    title = models.CharField(max_length=255)
    address = models.TextField()
    employees_number = models.IntegerField(null=True, blank=True)
    is_hunting = models.BooleanField(default=True)

    def __str__(self):
        return self.title

worker/models.py
from django.db import models
from django.contrib.auth.models import User
class Worker(models.Model):
    user = models.OneToOneField(
        to=User,
        null=True,
        blank=False,
        on_delete=models.CASCADE
    )
    name = models.CharField(max_length=255)
    specialization = models.TextField()
    expected_salary = models.IntegerField (null=True, blank=True)
    def __str__(self):
        return self.name

class Comment(models.Model):
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    worker = models.ForeignKey(
        to=Worker,
        on_delete=models.CASCADE
    )
    author = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE
    )

    def __str__(self):
        return self.author.username

class Resume(models.Model):
    title = models.CharField(max_length=255)
    skillset = models.TextField()
    experience = models.IntegerField(null=True,blank=True)
    workplaces = models.TextField()
    resume = models.ForeignKey(
        to=Worker,
        on_delete=models.CASCADE
    )

core/views.py
from django.shortcuts import render, HttpResponse
from .models import Vacancy, Company
# Create your views here.
def homepage(request):
    return render(request=request, template_name="index.html")

def about(request):
    return HttpResponse("Найдите работу или работника мечты")

def contacts(request):
    return HttpResponse('''
    <div>
    Phone: +996777123456 <br>
    Email: office@handhunter.kg"
    </div>
    ''')

def address(request):
    return HttpResponse('''
    <ol>
    <li>Kievskaya-Sovetskaya</li>
    <li>Kurmanzhan-Datka-164</li>
    </ol>
    ''')

def vacancy_list(request):
    vacancies = Vacancy.objects.all()
    context = {'vacancies':vacancies}
    return render(request, 'vacancies.html', context)

def company_list(request):
    companies = Company.objects.all()
    context = {'companies':companies}
    return render(request, 'companies.html', context)

worker/views.py
from django.shortcuts import render
from .models import Worker
def worker_list(request):
    workers = Worker.objects.all()
    context = {'workers' :workers}
    return render(request, 'workers.html', context)

def worker_info(request,id):
    worker_object = Worker.objects.get(id=id)
    context = {'worker':worker_object}
    return render(request, 'worker.html', context)

core/templates/companies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Компании</h1>
    {% for v in companies %}
    <div>{{v.title}}</div>
    {% endfor %}
</body>
</html>

core/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Поиск работы и работников</h1>
    <div>
        Lorem10
    </div>
</body>
</html>

core/templates/vacancies.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Вакансии</h1>
    {% for v in vacancies %}
    <div>{{v.title}} - {{v.salary}}</div>
    {% endfor %}
</body>
</html>

worker/templates/worker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Информация о сотруднике</h1>
  <ul>
      <ol>Login: {{worker.user.username}}</ol>
    <ol>Имя: {{worker.name}}</ol>
    <ol>Специализация: {{worker.specialization}}</ol>
    <ol>Ожидаемая зарплата: {{worker.expected_salary}}</ol>
    <ol>Открыт для предложений: {{worker.is_searching}}</ol>
  </ul>

    <h2>Интересующие вакасии:</h2>
    {% for v in worker.vacancy_set.all %}
        <div>{{v.title}}</div>
    {% endfor %}
</body>
</html>

worker/templates/workers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
  <h1>Работники</h1>
    {% for v in workers %}
    <div>{{v.name}} - {{v.specialization}}</div>
    {% endfor %}
</body>
</html>